name: flutter_portfolio
description: A professional portfolio built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  animate_do: ^3.1.2
  flutter_svg: ^2.0.10
  email_launcher: ^1.1.1
  http: ^1.6.0
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true  
  assets:
    - assets/images/
    - assets/images/projects/
    - assets/images/jpmorgan.png
    - assets/images/tech/flutter.svg
    - assets/images/tech/dart.svg
    - assets/images/tech/firebase.svg
    - assets/images/tech/bloc.svg
    - assets/images/tech/java.svg
    - assets/images/tech/git.svg
    - assets/images/tech/mysql.svg
    - assets/images/tech/figma.svg
    - assets/images/tech/laravel.svg
    - assets/images/tech/androidstudio.svg
    - assets/images/tech/vscode.svg
    - assets/images/tech/vscode.svg
    - assets/files/
    - .env
